### ISSUE TITLE
[bug] After upgrading to v0.10.0 static map refuses to create static maps when uploading items via API

### ISSUE THREAD

**Issue by erral** [SamR1/FitTrackee#817]
### Checklist

- [x] Describe the bug.
- [x] Copy of the output/log.
- [x] Include your `.env` file.
- [x] Steps to Reproduce
- [ ] The exact command that failed. This is what you typed at the command line, including any options.
- [x] FitTrackee version, this is reported by `pip show fittrackee`
- [x] Operating System and Python Version
- [x] Installed Python packages

### Describe the bug

I have upgraded Fittrackee to v.0.10.0 (I am using docker)

I have run the script I use to download GPX files (now TCX files) from Garmin to upload them to Fittrackee, and when uploading them it fails.

I have tested with different tile providers and the error is the same

### Copy of the output/log

fittrackee     | 2025/05/29 17:05:16 - staticmap3.staticmap - ERROR - request failed [None]: https://b.tile.openstreetmap.fr/osmfr/13/4039/3010.png

fittrackee     | 2025/05/29 17:02:03 - staticmap3.staticmap - ERROR - request failed [None]: https://tile.openstreetmap.org/13/4039/3010.png

fittrackee  | 2025/05/29 16:55:12 - staticmap3.staticmap - ERROR - request failed [None]: https://tile.openstreetmap.org/13/4040/3005.png

### Include the .env file

APP_SECRET_KEY=`<REDACTED>`
DATABASE_URL=postgresql://postgres:postgres@fittrackee-db:5432/postgres
POSTGRES_USER=postgres
POSTGRES_PASSWORD=postgres
POSTGRES_DB=postgres
UI_URL=`https://<REDACTED>`
UPLOAD_FOLDER=/usr/src/app/
TILE_SERVER_URL=https://{s}.tile.openstreetmap.fr/osmfr/{z}/{x}/{y}.png
MAP_ATTRIBUTION='fond de carte par <a href="http://www.openstreetmap.fr/mentions-legales/" target="_blank" rel="nofollow noopener">OpenStreetMap France</a>, sous&nbsp;<a hre
f="http://creativecommons.org/licenses/by-sa/2.0/fr/" target="_blank" rel="nofollow noopener">licence CC BY-SA</a>'
STATICMAP_SUBDOMAINS=a,b,c

### FitTrackee Version

0.10.0

### Python Version

3.12

### FitTrackee installation method

With Docker image

### Operating System

GNU/Linux

**Comment by erral** [comment]
It also fails when uploading the file through the web interface. This is shown in the interface:

`error when generating map image`

And this in the container log:

`fittrackee     | 2025/05/29 17:25:15 - staticmap3.staticmap - ERROR - request failed [None]: https://a.tile.openstreetmap.fr/osmfr/13/4041/3011.png
`

**Comment by SamR1** [comment]
Hi,

A new environment variable must be set for **StaticMap** cache directory: [`STATICMAP_CACHE_DIR`](https://docs.fittrackee.org/en/installation.html#envvar-STATICMAP_CACHE_DIR).

And the access rights to the directory must be updated in [docker-compose.yml](https://github.com/SamR1/FitTrackee/blob/master/docker-compose.yml):

```
    volumes:
      - ${UPLOAD_DIR:-./data/uploads}:/usr/src/app/uploads
      - ${LOG_DIR:-./data/logs}:/usr/src/app/logs
      - ${STATICMAP_CACHE_DIR:-./data/staticmap_cache}:/usr/src/app/.staticmap_cache
    post_start:
      - command: chown -R fittrackee:fittrackee /usr/src/app/uploads /usr/src/app/logs /usr/src/app/.staticmap_cache
        user: root
```
