### ISSUE TITLE
Map images block importing of gpx

### ISSUE THREAD

**Issue by Firesphere** [SamR1/FitTrackee#846]
When trying to add new workouts, I get an error.
In my logs, I see:
```
2025/06/20 04:17:00 - staticmap3.staticmap - ERROR - request failed [None]: https://tile.openstreetmap.org/14/16145/10259.png
```

I can get the image just fine using wget

FitTrackee details:
Version : FitTrackee v0.10.3 (Docker latest)
DB: Postgresql 16
Server details:
```
$ neowofetch --stdout
ubuntu@Lada 
----------- 
OS: Ubuntu trixie/sid (noble) aarch64 
Host: KVM Virtual Machine virt-4.2 
Kernel: 6.8.0-1026-oracle 
Uptime: 1 day, 7 hours, 28 mins 
Packages: 616 (dpkg), 3 (snap) 
Shell: bash 5.2.21 
Resolution: 1024x768 
Terminal: /dev/pts/0 
CPU: ARM Neoverse-N1 (4) 
GPU: Red Hat, Inc. Virtio 1.0 GPU 
Memory: 1.01 GiB / 23.41 GiB (4%) 
Network: Unknown 
BIOS: EFI Development Kit II / OVMF 0.0 (08/22/2023) 

```
```
$ lscpu
Architecture:             aarch64
  CPU op-mode(s):         32-bit, 64-bit
  Byte Order:             Little Endian
CPU(s):                   4
  On-line CPU(s) list:    0-3
Vendor ID:                ARM
  Model name:             Neoverse-N1
    Model:                1
    Thread(s) per core:   1
    Core(s) per socket:   4
    Socket(s):            1
    Stepping:             r3p1
    BogoMIPS:             50.00
    Flags:                fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop asimddp ssbs
NUMA:                     
  NUMA node(s):           1
  NUMA node0 CPU(s):      0-3
```
```
$ free -h
               total        used        free      shared  buff/cache   available
Mem:            23Gi       1.0Gi        20Gi        23Mi       2.3Gi        22Gi
Swap:             0B          0B          0B
```

**Comment by SamR1** [comment]
Hi,

Has the owner of the cache directory ([`STATICMAP_CACHE_DIR`](https://docs.fittrackee.org/en/installation.html#envvar-STATICMAP_CACHE_DIR)) been updated?

Example in [docker-compose.yml](https://github.com/SamR1/FitTrackee/blob/master/docker-compose.yml):

```
    volumes:
      - ${UPLOAD_DIR:-./data/uploads}:/usr/src/app/uploads
      - ${LOG_DIR:-./data/logs}:/usr/src/app/logs
      - ${STATICMAP_CACHE_DIR:-./data/staticmap_cache}:/usr/src/app/.staticmap_cache
    post_start:
      - command: chown -R fittrackee:fittrackee /usr/src/app/uploads /usr/src/app/logs /usr/src/app/.staticmap_cache
        user: root
```
