### ISSUE TITLE
[bug] Cant download map images during upload

### ISSUE THREAD

**Issue by cutec-chris** [SamR1/FitTrackee#848]
### Checklist

- [x] Describe the bug.
- [x] Copy of the output/log.
- [ ] Include your `.env` file.
- [x] Steps to Reproduce
- [ ] The exact command that failed. This is what you typed at the command line, including any options.
- [x] FitTrackee version, this is reported by `pip show fittrackee`
- [x] Operating System and Python Version
- [ ] Installed Python packages

### Describe the bug

Since 3 weeks all uploads fails. 
when i use the download url within the container with wget, i can download the tile

### Copy of the output/log

[fittrackee] | 2025/06/24 19:27:17 - fittrackee - WARNING - Redis not available, API rate limits are disabled.
[fittrackee] | 2025/06/24 19:27:17 - fittrackee - WARNING - EMAIL_URL is not provided, email sending is deactivated.
[fittrackee] | 2025/06/24 19:27:36 - staticmap3.staticmap - ERROR - request failed [None]: https://tile.openstreetmap.de/10/545/336.png
[fittrackee] | 2025/06/24 19:27:36 - staticmap3.staticmap - ERROR - request failed [None]: https://tile.openstreetmap.de/10/545/337.png
[fittrackee] | 2025/06/24 19:27:36 - staticmap3.staticmap - ERROR - request failed [None]: https://tile.openstreetmap.de/10/546/336.png
[fittrackee] | 2025/06/24 19:27:36 - staticmap3.staticmap - ERROR - request failed [None]: https://tile.openstreetmap.de/10/546/337.png
[fittrackee] | 2025/06/24 19:27:41 - staticmap3.staticmap - ERROR - request failed [None]: https://tile.openstreetmap.de/10/545/336.png

### FitTrackee Version

docker.io/fittrackee/fittrackee:latest

### Python Version

3.12

### FitTrackee installation method

From PyPI

### Operating System

GNU/Linux

**Comment by SamR1** [comment]
Hi,

[v0.10.0](https://github.com/SamR1/FitTrackee/releases/tag/v0.10.0) introduces a new env variable : [`STATICMAP_CACHE_DIR`](https://docs.fittrackee.org/en/installation.html#envvar-STATICMAP_CACHE_DIR).

With docker image, directory ownership must be updated.
Example in [docker-compose.yml](https://github.com/SamR1/FitTrackee/blob/master/docker-compose.yml#L40):

```
    volumes:
      - ${UPLOAD_DIR:-./data/uploads}:/usr/src/app/uploads
      - ${LOG_DIR:-./data/logs}:/usr/src/app/logs
      - ${STATICMAP_CACHE_DIR:-./data/staticmap_cache}:/usr/src/app/.staticmap_cache
    post_start:
      - command: chown -R fittrackee:fittrackee /usr/src/app/uploads /usr/src/app/logs /usr/src/app/.staticmap_cache
        user: root
```
